services:
  postit:
    image: postit
    build: 
      context: .
      dockerfile: ./postit/Dockerfile
    volumes:
      - ./postit:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080
    networks:
      - postit-network

networks:
  postit-network:
    driver: bridge